
// Code generated by stanc v2.27.0
#include <stan/model/model_header.hpp>
namespace tv_glm_hmm_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 91> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 73, column 4 to column 18)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 74, column 4 to column 25)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 76, column 4 to column 24)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 77, column 4 to column 25)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 82, column 4 to column 20)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 83, column 4 to column 28)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 86, column 8 to column 30)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 85, column 19 to line 87, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 85, column 4 to line 87, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 89, column 6 to column 18)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 91, column 8 to column 174)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 92, column 8 to column 25)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 90, column 20 to line 93, column 7)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 90, column 6 to line 93, column 7)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 88, column 4 to line 94, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 99, column 4 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 100, column 4 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 103, column 8 to column 49)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 105, column 8 to column 34)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 106, column 8 to column 34)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 102, column 19 to line 107, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 102, column 4 to line 107, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 110, column 6 to column 33)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 111, column 6 to column 23)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 109, column 18 to line 112, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 109, column 4 to line 112, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 52, column 4 to column 21)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 53, column 10 to column 11)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 53, column 4 to column 13)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 55, column 4 to column 21)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 58, column 4 to column 21)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 59, column 4 to column 21)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 60, column 4 to column 21)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 62, column 10 to column 11)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 62, column 4 to column 13)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 63, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 63, column 14 to column 15)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 63, column 4 to column 19)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 66, column 4 to column 21)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 67, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 67, column 14 to column 15)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 67, column 4 to column 19)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 73, column 12 to column 13)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 74, column 22 to column 23)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 74, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 76, column 21 to column 22)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 76, column 12 to column 13)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 77, column 22 to column 23)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 77, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 82, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 83, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 4, column 23 to column 24)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 4, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 4, column 4 to column 26)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 5, column 13 to column 14)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 5, column 4 to column 16)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 8, column 6 to column 48)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 7, column 18 to line 9, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 7, column 4 to line 9, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 14, column 10 to column 68)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 13, column 23 to line 15, column 9)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 13, column 8 to line 15, column 9)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 16, column 8 to column 42)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 12, column 21 to line 17, column 7)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 12, column 6 to line 17, column 7)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 11, column 19 to line 18, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 11, column 4 to line 18, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 20, column 4 to column 20)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 3, column 81 to line 21, column 3)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 26, column 23 to column 24)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 26, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 26, column 4 to column 26)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 27, column 19 to column 20)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 27, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 27, column 4 to column 22)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 28, column 19 to column 20)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 28, column 22 to column 23)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 28, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 28, column 4 to column 25)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 30, column 11 to column 12)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 30, column 4 to column 19)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 38, column 12 to column 34)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 39, column 12 to column 72)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 33, column 23 to line 40, column 9)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 33, column 8 to line 40, column 9)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 32, column 19 to line 42, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 32, column 4 to line 42, column 5)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 44, column 4 to column 48)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 45, column 4 to column 20)",
 " (in '/Users/marcpabst/Documents/Repositories/bayesian-mice-decisions/stan-models/tv-glm-hmm.stan', line 25, column 146 to line 46, column 3)"};


template <typename T2__, typename T3__, typename T4__>
std::vector<Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T2__>, T3__,
T4__>, -1, 1>>
forward(const int& K, const int& T, const T2__& logpi_arg__,
        const std::vector<std::vector<Eigen::Matrix<T3__, -1, 1>>>& logA,
        const std::vector<Eigen::Matrix<T4__, -1, 1>>& loglike,
        std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T2__>,
          T3__,
          T4__>;
  int current_statement__ = 0; 
  const auto& logpi = to_ref(logpi_arg__);
  static constexpr bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  try {
    current_statement__ = 52;
    validate_non_negative_index("logalpha", "K", K);
    current_statement__ = 53;
    validate_non_negative_index("logalpha", "T", T);
    std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> logalpha;
    logalpha = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(K, Eigen::Matrix<local_scalar_t__, -1, 1>(T));
    stan::math::fill(logalpha, DUMMY_VAR__);
    
    current_statement__ = 55;
    validate_non_negative_index("acc", "K", K);
    std::vector<local_scalar_t__> acc;
    acc = std::vector<local_scalar_t__>(K, DUMMY_VAR__);
    
    current_statement__ = 59;
    for (int j = 1; j <= K; ++j) {
      current_statement__ = 57;
      assign(logalpha,
        (rvalue(logpi, "logpi", index_uni(j)) +
          rvalue(loglike, "loglike", index_uni(j), index_uni(1))),
        "assigning variable logalpha", index_uni(j), index_uni(1));
    }
    current_statement__ = 67;
    for (int t = 2; t <= T; ++t) {
      current_statement__ = 65;
      for (int j = 1; j <= K; ++j) {
        current_statement__ = 62;
        for (int i = 1; i <= K; ++i) {
          current_statement__ = 60;
          assign(acc,
            ((rvalue(logalpha, "logalpha", index_uni(i), index_uni((t - 1)))
               +
               rvalue(logA, "logA", index_uni(t), index_uni(i), index_uni(j)))
              + rvalue(loglike, "loglike", index_uni(j), index_uni(t))),
            "assigning variable acc", index_uni(i));
        }
        current_statement__ = 63;
        assign(logalpha, log_sum_exp(acc),
          "assigning variable logalpha", index_uni(j), index_uni(t));
      }
    }
    current_statement__ = 68;
    return logalpha;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}

struct forward_functor__ {
template <typename T2__, typename T3__, typename T4__>
std::vector<Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T2__>, T3__,
T4__>, -1, 1>>
operator()(const int& K, const int& T, const T2__& logpi,
           const std::vector<std::vector<Eigen::Matrix<T3__, -1, 1>>>& logA,
           const std::vector<Eigen::Matrix<T4__, -1, 1>>& loglike,
           std::ostream* pstream__)  const 
{
return forward(K, T, logpi, logA, loglike, pstream__);
}
};

template <typename T2__, typename T3__, typename T4__, typename T5__,
typename T7__, typename T8__>
std::vector<Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T2__>, T3__,
stan::value_type_t<T4__>, stan::value_type_t<T5__>,
T7__, stan::promote_args_t<T8__>>, -1, 1>>
calculate_forward_values(const int& K, const int& T, const T2__& logpi_arg__,
                         const std::vector<Eigen::Matrix<T3__, -1, 1>>& baseP,
                         const T4__& x_arg__, const T5__& u_arg__,
                         const std::vector<int>& y,
                         const std::vector<Eigen::Matrix<T7__, -1, 1>>& betas_x,
                         const std::vector<Eigen::Matrix<T8__, -1, 1>>& betas_u,
                         std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T2__>,
          T3__,
          stan::value_type_t<T4__>,
          stan::value_type_t<T5__>,
          T7__, stan::promote_args_t<T8__>>;
  int current_statement__ = 0; 
  const auto& logpi = to_ref(logpi_arg__);
  const auto& x = to_ref(x_arg__);
  const auto& u = to_ref(u_arg__);
  static constexpr bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  try {
    current_statement__ = 70;
    validate_non_negative_index("logalpha", "K", K);
    current_statement__ = 71;
    validate_non_negative_index("logalpha", "T", T);
    std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> logalpha;
    logalpha = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(K, Eigen::Matrix<local_scalar_t__, -1, 1>(T));
    stan::math::fill(logalpha, DUMMY_VAR__);
    
    current_statement__ = 73;
    validate_non_negative_index("logb", "K", K);
    current_statement__ = 74;
    validate_non_negative_index("logb", "T", T);
    std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> logb;
    logb = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(K, Eigen::Matrix<local_scalar_t__, -1, 1>(T));
    stan::math::fill(logb, DUMMY_VAR__);
    
    current_statement__ = 76;
    validate_non_negative_index("logA", "T", T);
    current_statement__ = 77;
    validate_non_negative_index("logA", "K", K);
    current_statement__ = 78;
    validate_non_negative_index("logA", "K", K);
    std::vector<std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>> logA;
    logA = std::vector<std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>>(T, std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(K, Eigen::Matrix<local_scalar_t__, -1, 1>(K)));
    stan::math::fill(logA, DUMMY_VAR__);
    
    current_statement__ = 80;
    validate_non_negative_index("temp", "K", K);
    Eigen::Matrix<local_scalar_t__, -1, 1> temp;
    temp = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
    stan::math::fill(temp, DUMMY_VAR__);
    
    current_statement__ = 87;
    for (int t = 1; t <= T; ++t) {
      current_statement__ = 85;
      for (int i = 1; i <= K; ++i) {
        current_statement__ = 82;
        assign(logA, rvalue(baseP, "baseP", index_uni(i)),
          "assigning variable logA", index_uni(t), index_uni(i));
        current_statement__ = 83;
        assign(logb,
          bernoulli_logit_lpmf<false>(rvalue(y, "y", index_uni(t)),
            multiply(rvalue(x, "x", index_uni(t)),
              rvalue(betas_x, "betas_x", index_uni(i)))),
          "assigning variable logb", index_uni(i), index_uni(t));
      }
    }
    current_statement__ = 88;
    assign(logalpha, forward(K, T, logpi, logA, logb, pstream__),
      "assigning variable logalpha");
    current_statement__ = 89;
    return logalpha;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}

struct calculate_forward_values_functor__ {
template <typename T2__, typename T3__, typename T4__, typename T5__,
typename T7__, typename T8__>
std::vector<Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T2__>, T3__,
stan::value_type_t<T4__>, stan::value_type_t<T5__>,
T7__, stan::promote_args_t<T8__>>, -1, 1>>
operator()(const int& K, const int& T, const T2__& logpi,
           const std::vector<Eigen::Matrix<T3__, -1, 1>>& baseP,
           const T4__& x, const T5__& u, const std::vector<int>& y,
           const std::vector<Eigen::Matrix<T7__, -1, 1>>& betas_x,
           const std::vector<Eigen::Matrix<T8__, -1, 1>>& betas_u,
           std::ostream* pstream__)  const 
{
return calculate_forward_values(K, T, logpi, baseP, x, u, y, betas_x,
         betas_u, pstream__);
}
};

class tv_glm_hmm_model final : public model_base_crtp<tv_glm_hmm_model> {

 private:
  int N;
  std::vector<int> T;
  int K;
  int I;
  int R;
  int M;
  std::vector<int> y;
  Eigen::Matrix<double, -1, -1> x__;
  int P;
  Eigen::Matrix<double, -1, -1> u__; 
  Eigen::Map<Eigen::Matrix<double, -1, -1>> x{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> u{nullptr, 0, 0};
 
 public:
  ~tv_glm_hmm_model() { }
  
  inline std::string model_name() const final { return "tv_glm_hmm_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.27.0", "stancflags = "};
  }
  
  
  tv_glm_hmm_model(stan::io::var_context& context__,
                   unsigned int random_seed__ = 0,
                   std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "tv_glm_hmm_model_namespace::tv_glm_hmm_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 27;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 27;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 27;
      check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 28;
      validate_non_negative_index("T", "N", N);
      current_statement__ = 29;
      context__.validate_dims("data initialization","T","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      T = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 29;
      T = context__.vals_i("T");
      current_statement__ = 30;
      context__.validate_dims("data initialization","K","int",
           std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 30;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 30;
      check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 31;
      context__.validate_dims("data initialization","I","int",
           std::vector<size_t>{});
      I = std::numeric_limits<int>::min();
      
      current_statement__ = 31;
      I = context__.vals_i("I")[(1 - 1)];
      current_statement__ = 31;
      check_greater_or_equal(function__, "I", I, 0);
      current_statement__ = 32;
      context__.validate_dims("data initialization","R","int",
           std::vector<size_t>{});
      R = std::numeric_limits<int>::min();
      
      current_statement__ = 32;
      R = context__.vals_i("R")[(1 - 1)];
      current_statement__ = 32;
      check_greater_or_equal(function__, "R", R, 1);
      current_statement__ = 33;
      context__.validate_dims("data initialization","M","int",
           std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      
      current_statement__ = 33;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 33;
      check_greater_or_equal(function__, "M", M, 1);
      current_statement__ = 34;
      validate_non_negative_index("y", "I", I);
      current_statement__ = 35;
      context__.validate_dims("data initialization","y","int",
           std::vector<size_t>{static_cast<size_t>(I)});
      y = std::vector<int>(I, std::numeric_limits<int>::min());
      
      current_statement__ = 35;
      y = context__.vals_i("y");
      current_statement__ = 36;
      validate_non_negative_index("x", "I", I);
      current_statement__ = 37;
      validate_non_negative_index("x", "M", M);
      current_statement__ = 38;
      context__.validate_dims("data initialization","x","double",
           std::vector<size_t>{static_cast<size_t>(I),
            static_cast<size_t>(M)});
      x__ = Eigen::Matrix<double, -1, -1>(I, M);
      new (&x) Eigen::Map<Eigen::Matrix<double, -1, -1>>(x__.data(), I, M);
      
      {
        std::vector<local_scalar_t__> x_flat__;
        current_statement__ = 38;
        x_flat__ = context__.vals_r("x");
        current_statement__ = 38;
        pos__ = 1;
        current_statement__ = 38;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 38;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 38;
            assign(x, x_flat__[(pos__ - 1)],
              "assigning variable x", index_uni(sym2__), index_uni(sym1__));
            current_statement__ = 38;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 39;
      context__.validate_dims("data initialization","P","int",
           std::vector<size_t>{});
      P = std::numeric_limits<int>::min();
      
      current_statement__ = 39;
      P = context__.vals_i("P")[(1 - 1)];
      current_statement__ = 39;
      check_greater_or_equal(function__, "P", P, 1);
      current_statement__ = 40;
      validate_non_negative_index("u", "I", I);
      current_statement__ = 41;
      validate_non_negative_index("u", "P", P);
      current_statement__ = 42;
      context__.validate_dims("data initialization","u","double",
           std::vector<size_t>{static_cast<size_t>(I),
            static_cast<size_t>(P)});
      u__ = Eigen::Matrix<double, -1, -1>(I, P);
      new (&u) Eigen::Map<Eigen::Matrix<double, -1, -1>>(u__.data(), I, P);
      
      {
        std::vector<local_scalar_t__> u_flat__;
        current_statement__ = 42;
        u_flat__ = context__.vals_r("u");
        current_statement__ = 42;
        pos__ = 1;
        current_statement__ = 42;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          current_statement__ = 42;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 42;
            assign(u, u_flat__[(pos__ - 1)],
              "assigning variable u", index_uni(sym2__), index_uni(sym1__));
            current_statement__ = 42;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 43;
      validate_positive_index("pi", "K", K);
      current_statement__ = 44;
      validate_non_negative_index("betas_x", "K", K);
      current_statement__ = 45;
      validate_non_negative_index("betas_x", "M", M);
      current_statement__ = 46;
      validate_non_negative_index("baseP", "K", K);
      current_statement__ = 47;
      validate_positive_index("baseP", "K", K);
      current_statement__ = 48;
      validate_non_negative_index("betas_u", "K", K);
      current_statement__ = 49;
      validate_non_negative_index("betas_u", "P", P);
      current_statement__ = 50;
      validate_non_negative_index("logpi", "K", K);
      current_statement__ = 51;
      validate_non_negative_index("log_like_sess", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = (K - 1) + (K * M) + (K * (K - 1)) + (K * P);
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "tv_glm_hmm_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> pi;
      pi = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(pi, DUMMY_VAR__);
      
      current_statement__ = 1;
      pi = in__.template read_constrain_simplex<Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(
             lp__, K);
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> betas_x;
      betas_x = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(K, Eigen::Matrix<local_scalar_t__, -1, 1>(M));
      stan::math::fill(betas_x, DUMMY_VAR__);
      
      current_statement__ = 2;
      betas_x = in__.template read<std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>>(
                  K, M);
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> baseP;
      baseP = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(K, Eigen::Matrix<local_scalar_t__, -1, 1>(K));
      stan::math::fill(baseP, DUMMY_VAR__);
      
      current_statement__ = 3;
      baseP = in__.template read_constrain_simplex<std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>, jacobian__>(
                lp__, K, K);
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> betas_u;
      betas_u = std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(K, Eigen::Matrix<local_scalar_t__, -1, 1>(P));
      stan::math::fill(betas_u, DUMMY_VAR__);
      
      current_statement__ = 4;
      betas_u = in__.template read<std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>>(
                  K, P);
      Eigen::Matrix<local_scalar_t__, -1, 1> logpi;
      logpi = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(logpi, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> log_like_sess;
      log_like_sess = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(log_like_sess, DUMMY_VAR__);
      
      current_statement__ = 9;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 7;
        assign(logpi, stan::math::log(rvalue(pi, "pi", index_uni(k))),
          "assigning variable logpi", index_uni(k));
      }
      {
        int pos;
        pos = std::numeric_limits<int>::min();
        
        current_statement__ = 10;
        pos = 1;
        current_statement__ = 14;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 11;
          assign(log_like_sess,
            log_sum_exp(
              rvalue(
                calculate_forward_values(K, rvalue(T, "T", index_uni(n)), logpi, baseP,
  rvalue(x, "x",
    index_min_max(pos, ((pos + rvalue(T, "T", index_uni(n))) - 1)),
      index_omni()),
  rvalue(u, "u",
    index_min_max(pos, ((pos + rvalue(T, "T", index_uni(n))) - 1)),
      index_omni()),
  rvalue(y, "y",
    index_min_max(pos, ((pos + rvalue(T, "T", index_uni(n))) - 1))), betas_x,
  betas_u, pstream__),
                "calculate_forward_values(K, T[n], logpi, baseP, x[pos:((pos + T[n]) - 1), :],\nu[pos:((pos + T[n]) - 1), :], y[pos:((pos + T[n]) - 1)], betas_x,\nbetas_u)",
                index_omni(), index_uni(rvalue(T, "T", index_uni(n))))),
            "assigning variable log_like_sess", index_uni(n));
          current_statement__ = 12;
          pos = (pos + rvalue(T, "T", index_uni(n)));
        }
      }
      {
        int pos;
        pos = std::numeric_limits<int>::min();
        
        current_statement__ = 17;
        pos = 1;
        current_statement__ = 22;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 18;
          lp_accum__.add(
            dirichlet_lpdf<propto__>(
              rvalue(baseP, "baseP", index_uni(k), index_omni()),
              rep_vector(1, K)));
          current_statement__ = 19;
          lp_accum__.add(
            normal_lpdf<propto__>(rvalue(betas_x, "betas_x", index_uni(k)),
              0, 4));
          current_statement__ = 20;
          lp_accum__.add(
            normal_lpdf<propto__>(rvalue(betas_u, "betas_u", index_uni(k)),
              0, 4));
        }
        current_statement__ = 26;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 23;
          lp_accum__.add(rvalue(log_like_sess, "log_like_sess", index_uni(n)));
          current_statement__ = 24;
          pos = (pos + rvalue(T, "T", index_uni(n)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "tv_glm_hmm_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> pi;
      pi = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(pi, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      pi = in__.template read_constrain_simplex<Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(
             lp__, K);
      std::vector<Eigen::Matrix<double, -1, 1>> betas_x;
      betas_x = std::vector<Eigen::Matrix<double, -1, 1>>(K, Eigen::Matrix<double, -1, 1>(M));
      stan::math::fill(betas_x, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      betas_x = in__.template read<std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>>(
                  K, M);
      std::vector<Eigen::Matrix<double, -1, 1>> baseP;
      baseP = std::vector<Eigen::Matrix<double, -1, 1>>(K, Eigen::Matrix<double, -1, 1>(K));
      stan::math::fill(baseP, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      baseP = in__.template read_constrain_simplex<std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>, jacobian__>(
                lp__, K, K);
      std::vector<Eigen::Matrix<double, -1, 1>> betas_u;
      betas_u = std::vector<Eigen::Matrix<double, -1, 1>>(K, Eigen::Matrix<double, -1, 1>(P));
      stan::math::fill(betas_u, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      betas_u = in__.template read<std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>>(
                  K, P);
      Eigen::Matrix<double, -1, 1> logpi;
      logpi = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(logpi, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> log_like_sess;
      log_like_sess = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(log_like_sess, std::numeric_limits<double>::quiet_NaN());
      
      
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(pi[(sym1__ - 1)]);
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          vars__.emplace_back(betas_x[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          vars__.emplace_back(baseP[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          vars__.emplace_back(betas_u[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 9;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 7;
        assign(logpi, stan::math::log(rvalue(pi, "pi", index_uni(k))),
          "assigning variable logpi", index_uni(k));
      }
      {
        int pos;
        pos = std::numeric_limits<int>::min();
        
        current_statement__ = 10;
        pos = 1;
        current_statement__ = 14;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 11;
          assign(log_like_sess,
            log_sum_exp(
              rvalue(
                calculate_forward_values(K, rvalue(T, "T", index_uni(n)), logpi, baseP,
  rvalue(x, "x",
    index_min_max(pos, ((pos + rvalue(T, "T", index_uni(n))) - 1)),
      index_omni()),
  rvalue(u, "u",
    index_min_max(pos, ((pos + rvalue(T, "T", index_uni(n))) - 1)),
      index_omni()),
  rvalue(y, "y",
    index_min_max(pos, ((pos + rvalue(T, "T", index_uni(n))) - 1))), betas_x,
  betas_u, pstream__),
                "calculate_forward_values(K, T[n], logpi, baseP, x[pos:((pos + T[n]) - 1), :],\nu[pos:((pos + T[n]) - 1), :], y[pos:((pos + T[n]) - 1)], betas_x,\nbetas_u)",
                index_omni(), index_uni(rvalue(T, "T", index_uni(n))))),
            "assigning variable log_like_sess", index_uni(n));
          current_statement__ = 12;
          pos = (pos + rvalue(T, "T", index_uni(n)));
        }
      }
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          vars__.emplace_back(logpi[(sym1__ - 1)]);
        }
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          vars__.emplace_back(log_like_sess[(sym1__ - 1)]);
        }
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    int current_statement__ = 0; 
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, 1> pi;
      pi = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(pi, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> pi_flat__;
        current_statement__ = 1;
        pi_flat__ = context__.vals_r("pi");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          assign(pi, pi_flat__[(pos__ - 1)],
            "assigning variable pi", index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      Eigen::Matrix<double, -1, 1> pi_free__;
      pi_free__ = Eigen::Matrix<double, -1, 1>((K - 1));
      stan::math::fill(pi_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      assign(pi_free__, stan::math::simplex_free(pi),
        "assigning variable pi_free__");
      std::vector<Eigen::Matrix<double, -1, 1>> betas_x;
      betas_x = std::vector<Eigen::Matrix<double, -1, 1>>(K, Eigen::Matrix<double, -1, 1>(M));
      stan::math::fill(betas_x, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> betas_x_flat__;
        current_statement__ = 2;
        betas_x_flat__ = context__.vals_r("betas_x");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 2;
            assign(betas_x, betas_x_flat__[(pos__ - 1)],
              "assigning variable betas_x", index_uni(sym2__),
                                              index_uni(sym1__));
            current_statement__ = 2;
            pos__ = (pos__ + 1);
          }
        }
      }
      std::vector<Eigen::Matrix<double, -1, 1>> baseP;
      baseP = std::vector<Eigen::Matrix<double, -1, 1>>(K, Eigen::Matrix<double, -1, 1>(K));
      stan::math::fill(baseP, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> baseP_flat__;
        current_statement__ = 3;
        baseP_flat__ = context__.vals_r("baseP");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 3;
            assign(baseP, baseP_flat__[(pos__ - 1)],
              "assigning variable baseP", index_uni(sym2__),
                                            index_uni(sym1__));
            current_statement__ = 3;
            pos__ = (pos__ + 1);
          }
        }
      }
      std::vector<Eigen::Matrix<double, -1, 1>> baseP_free__;
      baseP_free__ = std::vector<Eigen::Matrix<double, -1, 1>>(K, Eigen::Matrix<double, -1, 1>(
        (K - 1)));
      stan::math::fill(baseP_free__, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 3;
        assign(baseP_free__, stan::math::simplex_free(baseP[(sym1__ - 1)]),
          "assigning variable baseP_free__", index_uni(sym1__));
      }
      std::vector<Eigen::Matrix<double, -1, 1>> betas_u;
      betas_u = std::vector<Eigen::Matrix<double, -1, 1>>(K, Eigen::Matrix<double, -1, 1>(P));
      stan::math::fill(betas_u, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> betas_u_flat__;
        current_statement__ = 4;
        betas_u_flat__ = context__.vals_r("betas_u");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          current_statement__ = 4;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 4;
            assign(betas_u, betas_u_flat__[(pos__ - 1)],
              "assigning variable betas_u", index_uni(sym2__),
                                              index_uni(sym1__));
            current_statement__ = 4;
            pos__ = (pos__ + 1);
          }
        }
      }
      for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        vars__.emplace_back(pi_free__[(sym1__ - 1)]);
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          vars__.emplace_back(betas_x[(sym1__ - 1)][(sym2__ - 1)]);
        }
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= (K - 1); ++sym2__) {
          vars__.emplace_back(baseP_free__[(sym1__ - 1)][(sym2__ - 1)]);
        }
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= P; ++sym2__) {
          vars__.emplace_back(betas_u[(sym1__ - 1)][(sym2__ - 1)]);
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"pi", "betas_x", "baseP", "betas_u",
      "logpi", "log_like_sess"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(K)
                                                                   },
      std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(M)},
      std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(K)},
      std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(P)},
      std::vector<size_t>{static_cast<size_t>(K)},
      std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "pi" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "betas_x" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "baseP" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "betas_u" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "logpi" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_like_sess" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "pi" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "betas_x" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "baseP" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "betas_u" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "logpi" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_like_sess" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"pi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"betas_x\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "}},\"block\":\"parameters\"},{\"name\":\"baseP\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "}},\"block\":\"parameters\"},{\"name\":\"betas_u\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "}},\"block\":\"parameters\"},{\"name\":\"logpi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_like_sess\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"pi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((K - 1)) + "},\"block\":\"parameters\"},{\"name\":\"betas_x\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(M) + "}},\"block\":\"parameters\"},{\"name\":\"baseP\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string((K - 1)) + "}},\"block\":\"parameters\"},{\"name\":\"betas_u\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "}},\"block\":\"parameters\"},{\"name\":\"logpi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_like_sess\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec;
      vars_vec.reserve(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars,
       emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec;
      params_r_vec.reserve(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }

};
}
using stan_model = tv_glm_hmm_model_namespace::tv_glm_hmm_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return tv_glm_hmm_model_namespace::profiles__;
}

#endif


