name: Advanced Usage
on: push
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          echo "::set-output name=files::$(printf '%s ' *.md)"


          
      - name: run loop
        run: cd notes && for f in ${{ steps.files_list.outputs.files }}; do docker run --rm --volume "`pwd`:/data" --user `id -u`:`id -g` pandoc/latex:2.6 $f --output=$f.pdf; done

      - name: update file and push to remote    
        run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git add -A
                  git commit -m "Update test.txt"
                  git push